const users = [
  {
    id: 1,
    first_name: "Adolphus",
    last_name: "Crosskell",
    email: "acrosskell0@fc2.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/46.jpg",
    username: "acrosskell0",
    password: "acrosskell0",
  },
  {
    id: 2,
    first_name: "Ray",
    last_name: "Chris",
    email: "ray@gmail.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/42.jpg",
    username: "raychris",
    password: "raychris",
  },
  {
    id: 3,
    first_name: "Nguyen",
    last_name: "An",
    email: "nguyenan@gmail.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/30.jpg",
    username: "nguyenan",
    password: "nguyenan",
  },
  {
    id: 4,
    first_name: "Hoang",
    last_name: "Anh",
    email: "hoanganh@gmail.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/29.jpg",
    username: "hoanganh",
    password: "hoanganh",
  },
  {
    id: 5,
    first_name: "Nolan",
    last_name: "Christophe",
    email: "nolan@gmail.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/47.jpg",
    username: "nolan90",
    password: "nolan90",
  },
  {
    id: 6,
    first_name: "Oscar",
    last_name: "Thomas",
    email: "oscar@gmail.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/36.jpg",
    username: "oscar",
    password: "oscar",
  },
  {
    id: 7,
    first_name: "Katharine",
    last_name: "McNa",
    email: "katharine@gmail.com",
    avatarUrl:
      "https://m.media-amazon.com/images/M/MV5BOThhZTkxMWMtY2UyYS00MTdlLTk1ZmMtZWQ0OWFkZjE2YTA1XkEyXkFqcGdeQXVyMjU0ODI4MzY@._V1_UX172_CR0,0,172,256_AL_.jpg",
    username: "katharine",
    password: "katharine",
  },
  {
    id: 8,
    first_name: "Ngoc",
    last_name: "Anh",
    email: "ngocanh@gmail.com",
    avatarUrl: "https://randomuser.me/api/portraits/women/50.jpg",
    username: "ngocanh",
    password: "ngocanh",
  },
  {
    id: 9,
    first_name: "Ana",
    last_name: "Armas",
    email: "Ana@gmail.com",
    avatarUrl:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3NjYzMzE1MV5BMl5BanBnXkFtZTgwNTA4NDY4OTE@._V1_UX172_CR0,0,172,256_AL_.jpg",
    username: "anaarmas",
    password: "anaarmas",
  },
  {
    id: 10,
    first_name: "Della",
    last_name: "Case",
    email: "della@gmail.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1510227272981-87123e259b17?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&s=3759e09a5b9fbe53088b23c615b6312e",
    username: "della",
    password: "della",
  },
  {
    id: 11,
    first_name: "Hoang",
    last_name: "Thiem",
    email: "hcaothiem@gmail.com",
    avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    username: "admin",
    password: "admin",
  },
  {
    id: 12,
    first_name: "Laurella",
    last_name: "Streeting",
    email: "lstreetingb@shinystat.com",
    avatarUrl: "https://robohash.org/quisquamoditnihil.png?size=50x50&set=set1",
    username: "lstreetingb",
    password: "65W48v1Biu",
  },
  {
    id: 13,
    first_name: "Rhiamon",
    last_name: "March",
    email: "rmarchc@facebook.com",
    avatarUrl:
      "https://robohash.org/cumqueteneturasperiores.png?size=50x50&set=set1",
    username: "rmarchc",
    password: "pkmJ4IV",
  },
  {
    id: 14,
    first_name: "Titos",
    last_name: "Attack",
    email: "tattackd@mozilla.com",
    avatarUrl: "https://robohash.org/iureutvoluptate.jpg?size=50x50&set=set1",
    username: "tattackd",
    password: "rFMhBMmphX",
  },
  {
    id: 15,
    first_name: "Eugenia",
    last_name: "Mazin",
    email: "emazine@sfgate.com",
    avatarUrl: "https://robohash.org/autidquos.png?size=50x50&set=set1",
    username: "emazine",
    password: "hFLlF4NN",
  },
  {
    id: 16,
    first_name: "Frasquito",
    last_name: "MacAlpine",
    email: "fmacalpinef@joomla.org",
    avatarUrl: "https://robohash.org/autquodquibusdam.bmp?size=50x50&set=set1",
    username: "fmacalpinef",
    password: "CAgael9JXF6J",
  },
  {
    id: 17,
    first_name: "Tanitansy",
    last_name: "Sturton",
    email: "tsturtong@issuu.com",
    avatarUrl: "https://robohash.org/eligendiametest.png?size=50x50&set=set1",
    username: "tsturtong",
    password: "1J4aKx1f7",
  },
  {
    id: 18,
    first_name: "Patten",
    last_name: "Pinchon",
    email: "ppinchonh@house.gov",
    avatarUrl:
      "https://robohash.org/consecteturvoluptatemanimi.jpg?size=50x50&set=set1",
    username: "ppinchonh",
    password: "eUW5aIQlfUW",
  },
  {
    id: 19,
    first_name: "Emmi",
    last_name: "Hughland",
    email: "ehughlandi@stanford.edu",
    avatarUrl: "https://robohash.org/deseruntetest.bmp?size=50x50&set=set1",
    username: "ehughlandi",
    password: "kjwiv78X",
  },
  {
    id: 20,
    first_name: "Amery",
    last_name: "Lathwell",
    email: "alathwellj@time.com",
    avatarUrl: "https://robohash.org/eiusquireiciendis.bmp?size=50x50&set=set1",
    username: "alathwellj",
    password: "kat9UHXIR6Jd",
  },
  {
    id: 21,
    first_name: "Rasia",
    last_name: "Lievesley",
    email: "rlievesleyk@creativecommons.org",
    avatarUrl: "https://robohash.org/namvitaedeserunt.jpg?size=50x50&set=set1",
    username: "rlievesleyk",
    password: "S2DhJd5H3G5A",
  },
  {
    id: 22,
    first_name: "Tatum",
    last_name: "Casey",
    email: "tcaseyl@4shared.com",
    avatarUrl: "https://robohash.org/eaomnisdoloribus.bmp?size=50x50&set=set1",
    username: "tcaseyl",
    password: "49Zxvu",
  },
  {
    id: 23,
    first_name: "Claresta",
    last_name: "Jerrams",
    email: "cjerramsm@java.com",
    avatarUrl:
      "https://robohash.org/doloremquemodimaiores.bmp?size=50x50&set=set1",
    username: "cjerramsm",
    password: "39JPjiKUOuW",
  },
  {
    id: 24,
    first_name: "Cami",
    last_name: "Cranson",
    email: "ccransonn@yellowbook.com",
    avatarUrl: "https://robohash.org/voluptatemutullam.jpg?size=50x50&set=set1",
    username: "ccransonn",
    password: "lqAU8pogg",
  },
  {
    id: 25,
    first_name: "Kathrine",
    last_name: "Colter",
    email: "kcoltero@constantcontact.com",
    avatarUrl:
      "https://robohash.org/errordistinctiosunt.bmp?size=50x50&set=set1",
    username: "kcoltero",
    password: "RLLCDs",
  },
  {
    id: 26,
    first_name: "Arlana",
    last_name: "Aloshikin",
    email: "aaloshikinp@businesswire.com",
    avatarUrl:
      "https://robohash.org/optiofugiattempore.png?size=50x50&set=set1",
    username: "aaloshikinp",
    password: "5DsufJJUHGN",
  },
  {
    id: 27,
    first_name: "Fleur",
    last_name: "Lathey",
    email: "flatheyq@gov.uk",
    avatarUrl:
      "https://robohash.org/magnamquidemitaque.png?size=50x50&set=set1",
    username: "flatheyq",
    password: "VEZdQcMv",
  },
  {
    id: 28,
    first_name: "Karalynn",
    last_name: "Shepeard",
    email: "kshepeardr@bluehost.com",
    avatarUrl: "https://robohash.org/dolorametrerum.jpg?size=50x50&set=set1",
    username: "kshepeardr",
    password: "NLvMjgQ5I9",
  },
  {
    id: 29,
    first_name: "Hesther",
    last_name: "Puttergill",
    email: "hputtergills@hhs.gov",
    avatarUrl:
      "https://robohash.org/cupiditatesaepeerror.bmp?size=50x50&set=set1",
    username: "hputtergills",
    password: "MfFfk3Gb8",
  },
  {
    id: 30,
    first_name: "Sibyl",
    last_name: "Fuxman",
    email: "sfuxmant@unesco.org",
    avatarUrl: "https://robohash.org/utdolorumtotam.bmp?size=50x50&set=set1",
    username: "sfuxmant",
    password: "mDt68M",
  },
  {
    id: 31,
    first_name: "Levi",
    last_name: "Cheine",
    email: "lcheineu@tmall.com",
    avatarUrl:
      "https://robohash.org/numquamomnisbeatae.bmp?size=50x50&set=set1",
    username: "lcheineu",
    password: "bd8KR8bJZvIz",
  },
  {
    id: 32,
    first_name: "Eberhard",
    last_name: "Tiller",
    email: "etillerv@google.it",
    avatarUrl:
      "https://robohash.org/accusantiumnesciuntarchitecto.bmp?size=50x50&set=set1",
    username: "etillerv",
    password: "p9nVTEfXM",
  },
  {
    id: 33,
    first_name: "Janaya",
    last_name: "Footer",
    email: "jfooterw@ustream.tv",
    avatarUrl: "https://robohash.org/rerumutfugit.jpg?size=50x50&set=set1",
    username: "jfooterw",
    password: "NFtFd2bk2ZQ",
  },
  {
    id: 34,
    first_name: "Pryce",
    last_name: "Letixier",
    email: "pletixierx@altervista.org",
    avatarUrl:
      "https://robohash.org/excepturisimiliqueculpa.jpg?size=50x50&set=set1",
    username: "pletixierx",
    password: "RHTMhrem",
  },
  {
    id: 35,
    first_name: "Carlene",
    last_name: "Buglass",
    email: "cbuglassy@cam.ac.uk",
    avatarUrl:
      "https://robohash.org/aspernaturremnatus.jpg?size=50x50&set=set1",
    username: "cbuglassy",
    password: "3i1Xpe4MSi",
  },
  {
    id: 36,
    first_name: "Sollie",
    last_name: "Feye",
    email: "sfeyez@topsy.com",
    avatarUrl:
      "https://robohash.org/dignissimosvoluptatesaut.jpg?size=50x50&set=set1",
    username: "sfeyez",
    password: "Q3Xtycw",
  },
  {
    id: 37,
    first_name: "Stuart",
    last_name: "Spencelayh",
    email: "sspencelayh10@nymag.com",
    avatarUrl:
      "https://robohash.org/quasifacilisreiciendis.jpg?size=50x50&set=set1",
    username: "sspencelayh10",
    password: "IGryrTuaSM",
  },
  {
    id: 38,
    first_name: "Janaya",
    last_name: "Egar",
    email: "jegar11@ihg.com",
    avatarUrl:
      "https://robohash.org/optionostrumreiciendis.jpg?size=50x50&set=set1",
    username: "jegar11",
    password: "YFMNoPU",
  },
  {
    id: 39,
    first_name: "Rani",
    last_name: "Fiennes",
    email: "rfiennes12@dion.ne.jp",
    avatarUrl: "https://robohash.org/ducimusquiseos.png?size=50x50&set=set1",
    username: "rfiennes12",
    password: "pNkRDwPFff3x",
  },
  {
    id: 40,
    first_name: "Winnie",
    last_name: "Tudge",
    email: "wtudge13@ow.ly",
    avatarUrl:
      "https://robohash.org/consequaturfacerequi.jpg?size=50x50&set=set1",
    username: "wtudge13",
    password: "VntdN0iRDPhS",
  },
  {
    id: 41,
    first_name: "Rory",
    last_name: "Kubacek",
    email: "rkubacek14@msu.edu",
    avatarUrl:
      "https://robohash.org/officiisrationenihil.jpg?size=50x50&set=set1",
    username: "rkubacek14",
    password: "qaI2nppkzYNH",
  },
  {
    id: 42,
    first_name: "Dyna",
    last_name: "Gavagan",
    email: "dgavagan15@ebay.com",
    avatarUrl:
      "https://robohash.org/voluptasnamvoluptates.jpg?size=50x50&set=set1",
    username: "dgavagan15",
    password: "6Sh4TXQtJ",
  },
  {
    id: 43,
    first_name: "Wyndham",
    last_name: "Fullard",
    email: "wfullard16@newsvine.com",
    avatarUrl:
      "https://robohash.org/laboriosamlaudantiumlabore.bmp?size=50x50&set=set1",
    username: "wfullard16",
    password: "TN28KvmQ7Ns",
  },
  {
    id: 44,
    first_name: "Gasparo",
    last_name: "Wattins",
    email: "gwattins17@google.pl",
    avatarUrl:
      "https://robohash.org/quosperspiciatisin.bmp?size=50x50&set=set1",
    username: "gwattins17",
    password: "ihb6lZrEf",
  },
  {
    id: 45,
    first_name: "Andria",
    last_name: "Willarton",
    email: "awillarton18@dailymotion.com",
    avatarUrl:
      "https://robohash.org/teneturaperiamnesciunt.png?size=50x50&set=set1",
    username: "awillarton18",
    password: "d9URrf",
  },
  {
    id: 46,
    first_name: "Lilia",
    last_name: "Cherry Holme",
    email: "lcherryholme19@sfgate.com",
    avatarUrl:
      "https://robohash.org/namvoluptasincidunt.png?size=50x50&set=set1",
    username: "lcherryholme19",
    password: "I15WMG",
  },
  {
    id: 47,
    first_name: "Dorthy",
    last_name: "Romain",
    email: "dromain1a@theatlantic.com",
    avatarUrl: "https://robohash.org/ipsumdoloret.bmp?size=50x50&set=set1",
    username: "dromain1a",
    password: "WeQpCFNklS",
  },
  {
    id: 48,
    first_name: "Cynde",
    last_name: "Readitt",
    email: "creaditt1b@aol.com",
    avatarUrl: "https://robohash.org/beataequisa.jpg?size=50x50&set=set1",
    username: "creaditt1b",
    password: "BpxlcMY",
  },
  {
    id: 49,
    first_name: "Celene",
    last_name: "Pettitt",
    email: "cpettitt1c@seattletimes.com",
    avatarUrl:
      "https://robohash.org/iustoomnisvoluptates.jpg?size=50x50&set=set1",
    username: "cpettitt1c",
    password: "kmkpivv",
  },
  {
    id: 50,
    first_name: "Mae",
    last_name: "Wloch",
    email: "mwloch1d@paginegialle.it",
    avatarUrl:
      "https://robohash.org/officiatemporibusut.png?size=50x50&set=set1",
    username: "mwloch1d",
    password: "9jrnWJ",
  },
];

module.exports = { users };
