export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const KEEP_SIGNED_SUCCESS = "KEEP_SIGNED_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const LOGOUT = "LOGOUT";
